version: '{build}'
image:
- Visual Studio 2017
configuration:
- Debug
platform:
- x64
environment:
  matrix:
  - arch: Win64
matrix:
  fast_finish: true

before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake ../src -G "Visual Studio 15 2017 Win64"
build:
  project: build\simplecompiler.sln
  verbosity: minimal
  parallel: true
